version: "3.8"

services:
  app:
    environment:
      - GHOST_URL
      - GHOST_CONTENT_API_KEY_FILE=/run/secrets/ghost_content_api_key
      - GHOST_ADMIN_API_KEY_FILE=/run/secrets/ghost_admin_api_key
      - GHOST_WEBHOOK_SECRET_FILE=/run/secrets/ghost_webhook_secret
    secrets:
      - ghost_content_api_key
      - ghost_admin_api_key
      - ghost_webhook_secret

secrets:
  ghost_content_api_key:
    external: true
    name: ${STACK_NAME}_ghost_content_api_key_${SECRET_GHOST_CONTENT_API_KEY_VERSION:-v1}
  ghost_admin_api_key:
    external: true
    name: ${STACK_NAME}_ghost_admin_api_key_${SECRET_GHOST_ADMIN_API_KEY_VERSION:-v1}
  ghost_webhook_secret:
    external: true
    name: ${STACK_NAME}_ghost_webhook_secret_${SECRET_GHOST_WEBHOOK_SECRET_VERSION:-v1}