version: "3.8"

services:
  app:
    environment:
      - ORCID_CLIENT_ID
      - ORCID_CLIENT_SECRET_FILE=/run/secrets/orchid_client_secret
    secrets:
      - orchid_client_secret

secrets:
  orchid_client_secret:
    external: true
    name: ${STACK_NAME}_orchid_client_secret_${SECRET_ORCID_CLIENT_SECRET_VERSION:-v1}
